### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by kmnft**
Add dlib installation steps to README and fix opencv to opencv-python in requirements.txt

### CODE REVIEW

**Comment by kmnft** [comment]
Also resize image and collect encodings only if face locations were found. This will improve encoding speed a little

**Comment by riya-17** [comment]
@kmnft Thanks for your contribution :) 
How do you intend to find face location?

**Comment by kmnft** [comment]
@riya-17 face_recognition API provides method to find face locations on unencoded image. If faces were found, it returns a list of face locations, if no faces were found, it returns an empty array. If no faces were found on given image, there is no point to encode this picture. 

Here is docs for face_recognition API:

https://face-recognition.readthedocs.io/en/latest/face_recognition.html#face_recognition.api.face_locations

**Comment by riya-17** [comment]
@kmnft your idea seems to be valid and good. would you like to work on this feature?

**Comment by kmnft** [comment]
@riya-17 I've already implemented it [here](https://github.com/riya-17/FaceRecognition/pull/16/commits/f83b956829abf97721d84ffe82f7d60f5802c73f). But I have some more improvements of encoder and I will create new pull request soon :)

**Comment by riya-17** [comment]
@kmnft Ok :)

**Pull request merged**
